[2025-03-11T18:09:35.690+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T18:09:35.896+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T18:09:31.184881+00:00 [queued]>
[2025-03-11T18:09:35.913+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T18:09:31.184881+00:00 [queued]>
[2025-03-11T18:09:35.916+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T18:09:35.942+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_minio> on 2025-03-11 18:09:31.184881+00:00
[2025-03-11T18:09:35.955+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T18:09:35.958+0000] {standard_task_runner.py:72} INFO - Started process 822 to run task
[2025-03-11T18:09:35.959+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'minio_dag', 'upload_to_minio', 'manual__2025-03-11T18:09:31.184881+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpk4ki87_i']
[2025-03-11T18:09:35.962+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask upload_to_minio
[2025-03-11T18:09:36.058+0000] {task_command.py:467} INFO - Running <TaskInstance: minio_dag.upload_to_minio manual__2025-03-11T18:09:31.184881+00:00 [running]> on host 864bdb0a156f
[2025-03-11T18:09:36.240+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_dag' AIRFLOW_CTX_TASK_ID='upload_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T18:09:31.184881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T18:09:31.184881+00:00'
[2025-03-11T18:09:36.242+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T18:09:36.243+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T18:09:36.244+0000] {logging_mixin.py:190} INFO - Current task name:upload_to_minio state:running start_date:2025-03-11 18:09:35.898075+00:00
[2025-03-11T18:09:36.245+0000] {logging_mixin.py:190} INFO - Dag name:minio_dag and current dag run status:running
[2025-03-11T18:09:36.246+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T18:09:36.247+0000] {logging_mixin.py:190} INFO - DÃ©but de l'upload vers MinIO Ã  2025-03-11 18:09:36.247603
[2025-03-11T18:09:39.558+0000] {logging_mixin.py:190} INFO - ðŸš¨ Erreur lors de l'upload : Could not connect to the endpoint URL: "http://localhost:9001/test/test_file.txt"
[2025-03-11T18:09:39.559+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T18:09:39.573+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T18:09:39.574+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=minio_dag, task_id=upload_to_minio, run_id=manual__2025-03-11T18:09:31.184881+00:00, execution_date=20250311T180931, start_date=20250311T180935, end_date=20250311T180939
[2025-03-11T18:09:39.612+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T18:09:39.613+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T18:09:39.614+0000] {logging_mixin.py:190} INFO - Dag name:minio_dag queued_at:2025-03-11 18:09:31.206430+00:00
[2025-03-11T18:09:39.615+0000] {logging_mixin.py:190} INFO - Task hostname:864bdb0a156f operator:PythonOperator
[2025-03-11T18:09:39.662+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T18:09:39.703+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T18:09:39.708+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
